
services:
  tgbot:
    container_name: laohuangli
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./db:/db
    env_file:
      - .env
    ports:
      - "4090:80"
    restart: unless-stopped
